/* Abbonamento simulato collegato all'account Netlify. */
(function(){
  'use strict';
  if(window.__GENOVA_SUBSCRIPTION_V2__)return;
  window.__GENOVA_SUBSCRIPTION_V2__=true;

  var C={
    it:{guest:'Utente non collegato',login:'Accedi per abbonarti',subscribe:'Attiva Premium',benefits:'Vantaggi e prezzi',inactive:'Nessun abbonamento attivo',user:'Utente',manage:'Gestisci abbonamento',account:'Info account',title:'Genova mApp Premium',intro:'Scegli il piano che preferisci. In questa fase di prova l’attivazione è simulata e non viene effettuato alcun pagamento.',trial:'24 ore di prova incluse',month:'Mensile',year:'Annuale',monthPrice:'0,69 € al mese',yearPrice:'5,99 € all’anno',activate:'Attiva gratuitamente',b1:'Contenuti multimediali completi',b2:'Percorsi e materiali Premium',b3:'Accesso Premium verificato ogni 24 ore',active:'Abbonamento simulato attivo',plan:'Piano',trialUntil:'Prova fino al',renewal:'Rinnovo previsto',cancel:'Annulla abbonamento',keep:'Mantieni abbonamento',confirmCancel:'Vuoi disattivare l’abbonamento simulato?',cancelled:'Abbonamento disattivato.',working:'Operazione in corso…',error:'Operazione non riuscita. Controlla la connessione.',close:'Chiudi',simulated:'Modalità dimostrativa: nessun addebito.'},
    en:{guest:'User not logged in',login:'Log in to subscribe',subscribe:'Activate Premium',benefits:'Benefits and prices',inactive:'No active subscription',user:'User',manage:'Manage subscription',account:'Account info',title:'Genova mApp Premium',intro:'Choose your preferred plan. During this test phase activation is simulated and no payment is charged.',trial:'24-hour trial included',month:'Monthly',year:'Yearly',monthPrice:'€0.69 per month',yearPrice:'€5.99 per year',activate:'Activate for free',b1:'Full multimedia content',b2:'Premium routes and materials',b3:'Premium access checked every 24 hours',active:'Simulated subscription active',plan:'Plan',trialUntil:'Trial until',renewal:'Expected renewal',cancel:'Cancel subscription',keep:'Keep subscription',confirmCancel:'Do you want to disable the simulated subscription?',cancelled:'Subscription disabled.',working:'Working…',error:'The operation failed. Check your connection.',close:'Close',simulated:'Demo mode: no charge.'},
    es:{guest:'Usuario desconectado',login:'Accede para suscribirte',subscribe:'Activar Premium',benefits:'Ventajas y precios',inactive:'Sin suscripción activa',user:'Usuario',manage:'Gestionar suscripción',account:'Datos de la cuenta',title:'Genova mApp Premium',intro:'Elige el plan que prefieras. En esta fase de prueba la activación es simulada y no se realiza ningún pago.',trial:'Prueba de 24 horas incluida',month:'Mensual',year:'Anual',monthPrice:'0,69 € al mes',yearPrice:'5,99 € al año',activate:'Activar gratis',b1:'Contenido multimedia completo',b2:'Rutas y materiales Premium',b3:'Acceso Premium verificado cada 24 horas',active:'Suscripción simulada activa',plan:'Plan',trialUntil:'Prueba hasta',renewal:'Renovación prevista',cancel:'Cancelar suscripción',keep:'Mantener suscripción',confirmCancel:'¿Quieres desactivar la suscripción simulada?',cancelled:'Suscripción desactivada.',working:'Procesando…',error:'La operación ha fallado. Comprueba la conexión.',close:'Cerrar',simulated:'Modo demostración: sin cargos.'},
    fr:{guest:'Utilisateur non connecté',login:'Connectez-vous pour vous abonner',subscribe:'Activer Premium',benefits:'Avantages et tarifs',inactive:'Aucun abonnement actif',user:'Utilisateur',manage:'Gérer l’abonnement',account:'Infos du compte',title:'Genova mApp Premium',intro:'Choisissez votre formule. Pendant cette phase de test, l’activation est simulée et aucun paiement n’est effectué.',trial:'Essai de 24 heures inclus',month:'Mensuel',year:'Annuel',monthPrice:'0,69 € par mois',yearPrice:'5,99 € par an',activate:'Activer gratuitement',b1:'Contenus multimédias complets',b2:'Parcours et contenus Premium',b3:'Accès Premium vérifié toutes les 24 heures',active:'Abonnement simulé actif',plan:'Formule',trialUntil:'Essai jusqu’au',renewal:'Renouvellement prévu',cancel:'Annuler l’abonnement',keep:'Conserver l’abonnement',confirmCancel:'Voulez-vous désactiver l’abonnement simulé ?',cancelled:'Abonnement désactivé.',working:'Opération en cours…',error:'Échec de l’opération. Vérifiez la connexion.',close:'Fermer',simulated:'Mode démonstration : aucun débit.'},
    ar:{guest:'المستخدم غير مسجل الدخول',login:'سجّل الدخول للاشتراك',subscribe:'تفعيل Premium',benefits:'المزايا والأسعار',inactive:'لا يوجد اشتراك نشط',user:'المستخدم',manage:'إدارة الاشتراك',account:'معلومات الحساب',title:'Genova mApp Premium',intro:'اختر الخطة المناسبة. في هذه المرحلة التجريبية يكون التفعيل محاكاة ولا يتم تحصيل أي مبلغ.',trial:'تجربة لمدة 24 ساعة',month:'شهري',year:'سنوي',monthPrice:'0.69 € شهريًا',yearPrice:'5.99 € سنويًا',activate:'تفعيل مجاني',b1:'محتوى وسائط متعددة كامل',b2:'مسارات ومواد Premium',b3:'التحقق من Premium كل 24 ساعة',active:'الاشتراك التجريبي نشط',plan:'الخطة',trialUntil:'التجربة حتى',renewal:'التجديد المتوقع',cancel:'إلغاء الاشتراك',keep:'الاحتفاظ بالاشتراك',confirmCancel:'هل تريد إيقاف الاشتراك التجريبي؟',cancelled:'تم إيقاف الاشتراك.',working:'جارٍ التنفيذ…',error:'تعذر إتمام العملية. تحقق من الاتصال.',close:'إغلاق',simulated:'وضع تجريبي: دون رسوم.'},
    ru:{guest:'Пользователь не вошёл',login:'Войдите, чтобы подписаться',subscribe:'Активировать Premium',benefits:'Преимущества и цены',inactive:'Нет активной подписки',user:'Пользователь',manage:'Управление подпиской',account:'Данные аккаунта',title:'Genova mApp Premium',intro:'Выберите план. На этапе тестирования активация имитируется, оплата не взимается.',trial:'Пробный период 24 часа',month:'Месяц',year:'Год',monthPrice:'0,69 € в месяц',yearPrice:'5,99 € в год',activate:'Активировать бесплатно',b1:'Полный мультимедийный контент',b2:'Premium-маршруты и материалы',b3:'Проверка Premium каждые 24 часа',active:'Тестовая подписка активна',plan:'План',trialUntil:'Пробный период до',renewal:'Следующее продление',cancel:'Отменить подписку',keep:'Сохранить подписку',confirmCancel:'Отключить тестовую подписку?',cancelled:'Подписка отключена.',working:'Выполняется…',error:'Не удалось выполнить операцию. Проверьте подключение.',close:'Закрыть',simulated:'Демонстрационный режим: без списаний.'},
    zh:{guest:'用户未登录',login:'登录后订阅',subscribe:'激活 Premium',benefits:'权益与价格',inactive:'没有有效订阅',user:'用户',manage:'管理订阅',account:'账户信息',title:'Genova mApp Premium',intro:'请选择套餐。测试阶段仅模拟激活，不会收取任何费用。',trial:'包含 24 小时试用',month:'月度',year:'年度',monthPrice:'每月 0.69 €',yearPrice:'每年 5.99 €',activate:'免费激活',b1:'完整多媒体内容',b2:'Premium 路线与资料',b3:'每 24 小时验证 Premium 权限',active:'模拟订阅已激活',plan:'套餐',trialUntil:'试用期至',renewal:'预计续订',cancel:'取消订阅',keep:'保留订阅',confirmCancel:'要停用模拟订阅吗？',cancelled:'订阅已停用。',working:'正在处理…',error:'操作失败，请检查网络连接。',close:'关闭',simulated:'演示模式：不会扣费。'},
    lij:{guest:'Utente no collegou',login:'Intra pe abonâte',subscribe:'Ativa Premium',benefits:'Vantaggi e prezzi',inactive:'Nisciun abonamento ativo',user:'Utente',manage:'Gestisci l’abonamento',account:'Informaçioin account',title:'Genova mApp Premium',intro:'Çerni o pian che ti preferisci. Inte sta fase de preuva l’ativaçion a l’é simulâ e no gh’é nisciun pagamento.',trial:'24 oe de preuva incluse',month:'Menscile',year:'Annuâ',monthPrice:'0,69 € a-o meize',yearPrice:'5,99 € a l’anno',activate:'Ativa gratis',b1:'Contegnui multimedia completi',b2:'Percorsi e materiâ Premium',b3:'Accesso Premium verificou ògni 24 oe',active:'Abonamento simulou ativo',plan:'Pian',trialUntil:'Preuva finn-a-o',renewal:'Renovo previsto',cancel:'Leva l’abonamento',keep:'Mantegni l’abonamento',confirmCancel:'Ti veu disativâ l’abonamento simulou?',cancelled:'Abonamento disativou.',working:'Operaçion in corso…',error:'Operaçion no riescia. Contròlla a conescion.',close:'Særa',simulated:'Modalitæ demostrativa: nisciun adebito.'}
  };

  var btn,drop,modal,title,body,closeButton,rows,busy=false;
  function lang(){try{return String(localStorage.getItem('lang')||document.documentElement.lang||'it').toLowerCase().split(/[-_]/)[0];}catch(_e){return'it';}}
  function t(){return C[lang()]||C.it;}
  function account(){return window.GenovaAccount?window.GenovaAccount.getState():{user:null,subscription:null,active:false};}
  function name(user){var m=(user&&user.user_metadata)||{};return String(m.full_name||m.name||(user&&user.email||'').split('@')[0]||t().user);}
  function date(value){if(!value)return'—';try{return new Date(value).toLocaleString(lang()==='lij'?'it-IT':lang());}catch(_e){return new Date(value).toLocaleString();}}
  function node(tag,className,text){var el=document.createElement(tag);if(className)el.className=className;if(text!=null)el.textContent=text;return el;}
  function openModal(){modal.classList.remove('hidden');}
  function closeModal(){modal.classList.add('hidden');}
  function clearBody(){while(body.firstChild)body.removeChild(body.firstChild);}
  function accessRefresh(){var s=account();window.isSubscribed=!!s.active;try{if(typeof hidePaywall==='function')hidePaywall();if(typeof renderMedia==='function')renderMedia();}catch(_e){}document.dispatchEvent(new CustomEvent('genova:premium-ui',{detail:{active:!!s.active}}));}
  function render(){
    if(!btn)return;var s=account(),sub=s.subscription||{},active=!!s.active;
    btn.dataset.state=active?'gold':'silver';var img=btn.querySelector('img');if(img)img.src=active?'Abbonamento/coin-gold.svg':'Abbonamento/coin-silver.svg';
    var sr=btn.querySelector('.sr-only');if(sr)sr.textContent=active?t().active:(s.user?t().inactive:t().guest);
    if(!rows||rows.length<3)return;
    if(!s.user){rows[0].textContent=t().guest;rows[0].disabled=true;rows[1].textContent=t().login;rows[1].disabled=false;rows[1].dataset.action='login';rows[2].textContent=t().benefits;rows[2].disabled=false;rows[2].dataset.action='plans';}
    else if(!active){rows[0].textContent=t().user+': '+name(s.user);rows[0].disabled=true;rows[1].textContent=t().subscribe;rows[1].disabled=false;rows[1].dataset.action='plans';rows[2].textContent=t().benefits;rows[2].disabled=false;rows[2].dataset.action='plans';}
    else{rows[0].textContent=t().user+': '+name(s.user);rows[0].disabled=true;rows[1].textContent=t().manage;rows[1].disabled=false;rows[1].dataset.action='manage';rows[2].textContent=t().account;rows[2].disabled=false;rows[2].dataset.action='manage';}
    accessRefresh();
  }
  function benefitsList(){var ul=node('ul','sub-v2-benefits');[t().b1,t().b2,t().b3].forEach(function(value){ul.appendChild(node('li','',value));});return ul;}
  function showPlans(){
    title.textContent=t().title;clearBody();body.appendChild(node('p','sub-v2-intro',t().intro));body.appendChild(benefitsList());body.appendChild(node('p','sub-v2-trial',t().trial));
    var grid=node('div','sub-v2-plans');[['monthly',t().month,t().monthPrice],['yearly',t().year,t().yearPrice]].forEach(function(p){var card=node('article','sub-v2-plan');card.appendChild(node('h3','',p[1]));card.appendChild(node('strong','sub-v2-price',p[2]));var action=node('button','sub-v2-activate',t().activate);action.type='button';action.addEventListener('click',function(){activate(p[0],action);});card.appendChild(action);grid.appendChild(card);});body.appendChild(grid);body.appendChild(node('p','sub-v2-demo',t().simulated));openModal();
  }
  function showManage(message){
    var s=account(),sub=s.subscription||{};title.textContent=t().manage;clearBody();if(message)body.appendChild(node('p','sub-v2-message',message));body.appendChild(node('h3','sub-v2-active',t().active));
    var dl=node('dl','sub-v2-details');[[t().user,name(s.user)],[t().plan,sub.plan==='yearly'?t().year:t().month],[t().trialUntil,date(sub.trialEndsAt)],[t().renewal,date(sub.renewsAt)]].forEach(function(pair){dl.appendChild(node('dt','',pair[0]));dl.appendChild(node('dd','',pair[1]));});body.appendChild(dl);body.appendChild(node('p','sub-v2-demo',t().simulated));
    var cancel=node('button','sub-v2-cancel',t().cancel);cancel.type='button';cancel.addEventListener('click',showCancel);body.appendChild(cancel);openModal();
  }
  function showCancel(){title.textContent=t().cancel;clearBody();body.appendChild(node('p','sub-v2-intro',t().confirmCancel));var actions=node('div','sub-v2-confirm');var yes=node('button','sub-v2-cancel',t().cancel);var no=node('button','sub-v2-keep',t().keep);yes.addEventListener('click',cancelSubscription);no.addEventListener('click',function(){showManage();});actions.appendChild(yes);actions.appendChild(no);body.appendChild(actions);}
  async function activate(plan,button){if(busy)return;var s=account();if(!s.user){closeModal();if(window.GenovaAuth)window.GenovaAuth.open('login');return;}busy=true;button.disabled=true;button.textContent=t().working;try{await window.GenovaAccount.activateSubscription(plan);render();showManage();}catch(_e){button.disabled=false;button.textContent=t().error;}finally{busy=false;}}
  async function cancelSubscription(){if(busy)return;busy=true;var p=node('p','sub-v2-message',t().working);body.appendChild(p);try{await window.GenovaAccount.cancelSubscription();render();title.textContent=t().cancel;clearBody();body.appendChild(node('p','sub-v2-message',t().cancelled));var done=node('button','sub-v2-keep',t().close);done.addEventListener('click',closeModal);body.appendChild(done);}catch(_e){p.textContent=t().error;}finally{busy=false;}}
  function boot(){
    btn=document.getElementById('btn-sub');drop=document.getElementById('sub-dropdown');modal=document.getElementById('sub-modal');if(!btn||!drop||!modal)return;title=document.getElementById('sub-modal-title');body=document.getElementById('sub-modal-body');closeButton=modal.querySelector('.sub-modal-close');rows=drop.querySelectorAll('.sub-row');
    btn.addEventListener('click',function(event){event.preventDefault();drop.classList.toggle('open');btn.setAttribute('aria-expanded',drop.classList.contains('open')?'true':'false');});
    drop.addEventListener('click',function(event){var row=event.target.closest('.sub-row');if(!row||row.disabled)return;drop.classList.remove('open');var action=row.dataset.action;if(action==='login'){if(window.GenovaAuth)window.GenovaAuth.open('login');}else if(action==='manage')showManage();else showPlans();});
    document.addEventListener('click',function(event){if(!drop.contains(event.target)&&!btn.contains(event.target))drop.classList.remove('open');});
    closeButton.addEventListener('click',closeModal);modal.addEventListener('click',function(event){if(event.target===modal)closeModal();});
    document.addEventListener('genova:subscription-changed',render);document.addEventListener('genova:auth-changed',render);document.addEventListener('app:set-lang',render);render();
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
