(function(){
  'use strict';

  var museums = Array.isArray(window.MUSEI_DATA) ? window.MUSEI_DATA : (window.MUSEI_DATA = []);

  museums.push(
    {
      name: 'Museo Ebraico di Genova',
      lat: 44.412395,
      lng: 8.941737,
      img: 'musei/museo-ebraico-genova.jpg',
      address: 'Via Giovanni Bertora 6, Genova',
      url: 'https://www.museidigenova.it/it/museo-ebraico',
      genovaMappAccess: true,
      desc: {
        it: 'Il Museo Ebraico di Genova è ospitato all’interno della Sinagoga monumentale della città. Nato nel 2004, occupa gli spazi situati sotto la cupola e conserva opere di Emanuele Luzzati, oggetti di culto e testimonianze dedicate alla storia dell’ebraismo genovese e ligure. La visita permette di conoscere la presenza ebraica a Genova attraverso arte, documenti e memoria, approfondendo anche le vicende vissute dalla comunità durante le leggi razziali e la Shoah. Un luogo raccolto ma importante per comprendere una parte significativa della storia culturale e sociale della città e della Liguria.',
        en: 'The Jewish Museum of Genoa is housed inside the city’s monumental Synagogue. Founded in 2004, it occupies the spaces beneath the dome and preserves works by Emanuele Luzzati, ritual objects and exhibits devoted to the history of the Jewish community in Genoa and Liguria. Through art, documents and personal memories, the museum offers an insight into Jewish life in Genoa and also explores the experiences of the community during the period of the Italian racial laws and the Holocaust. Though relatively small, it is an important place for understanding a significant part of the cultural and social history of Genoa and Liguria.',
        es: 'El Museo Judío de Génova se encuentra en el interior de la monumental Sinagoga de la ciudad. Fundado en 2004, ocupa los espacios situados bajo la cúpula y conserva obras de Emanuele Luzzati, objetos de culto y testimonios dedicados a la historia del judaísmo genovés y ligur. A través del arte, los documentos y la memoria, la visita permite conocer la presencia judía en Génova y profundizar también en las experiencias de la comunidad durante las leyes raciales y la Shoá. Aunque de dimensiones reducidas, es un lugar importante para comprender una parte significativa de la historia cultural y social de Génova y de Liguria.',
        fr: 'Le Musée juif de Gênes est installé à l’intérieur de la synagogue monumentale de la ville. Créé en 2004, il occupe les espaces situés sous la coupole et conserve des œuvres d’Emanuele Luzzati, des objets de culte et des témoignages consacrés à l’histoire du judaïsme génois et ligure. À travers l’art, les documents et la mémoire, la visite permet de découvrir la présence juive à Gênes et d’approfondir également l’histoire de la communauté pendant la période des lois raciales et de la Shoah. De dimensions modestes, le musée constitue néanmoins un lieu important pour comprendre une partie significative de l’histoire culturelle et sociale de Gênes et de la Ligurie.',
        ar: 'يقع المتحف اليهودي في جنوة داخل الكنيس الكبير التاريخي في المدينة. تأسس المتحف عام 2004 ويشغل المساحات الواقعة تحت القبة، ويضم أعمالاً للفنان إيمانويل لوتساتي، وأدوات دينية، وشهادات ووثائق مخصصة لتاريخ اليهودية في جنوة وليغوريا. تتيح الزيارة التعرف على الحضور اليهودي في المدينة من خلال الفن والوثائق والذاكرة، كما تتناول الأحداث التي عاشتها الجالية خلال فترة القوانين العنصرية والمحرقة. وعلى الرغم من صغر حجم المتحف، فإنه يمثل مكاناً مهماً لفهم جانب بارز من التاريخ الثقافي والاجتماعي لجنوة وليغوريا.',
        ru: 'Еврейский музей Генуи расположен в здании монументальной городской синагоги. Музей был открыт в 2004 году и занимает помещения под куполом. Здесь хранятся произведения Эмануэле Луццати, предметы религиозного культа, документы и свидетельства, посвящённые истории еврейской общины Генуи и Лигурии. Экспозиция рассказывает о присутствии евреев в городе через искусство, документы и историческую память, уделяя особое внимание событиям периода расовых законов и Холокоста. Несмотря на небольшие размеры, музей имеет большое значение для понимания важной части культурной и общественной истории Генуи и Лигурии.',
        zh: '热那亚犹太博物馆位于城市宏伟的犹太会堂内。博物馆成立于2004年，展区设在穹顶下方，收藏有埃马努埃莱·卢扎蒂的作品、宗教礼仪用品，以及介绍热那亚和利古里亚犹太历史的文献与见证资料。参观者可以通过艺术品、历史文件和记忆资料了解犹太社群在热那亚的发展，同时深入认识该社群在种族法时期以及大屠杀期间的经历。博物馆规模不大，却是了解热那亚及利古里亚文化与社会历史中重要一章的珍贵场所。',
        lij: 'O Museo Ebraico de Zena o l’é ospitò inta Sinagòga monumentâ da çittæ. Nascio into 2004, o l’occupa i spaçi sotta a cupola e o conserva euvie de Emanuele Luzzati, oggetti do culto e testimonianze dedicate a-a stöia de l’ebraismo zeneize e ligure. A visita a permette de conosce a presenza ebraica a Zena attraverso l’arte, i documenti e a memöia, approfondendo ascì e vicende da comunitæ durante e lezzi razziali e a Shoah. Anche se o l’é un museo de dimension contenûe, o rappresenta un luogo importante pe capî unna parte significativa da stöia culturâ e sociale de Zena e da Liguria.'
      },
      access: {it:'Temporaneamente chiuso.',en:'Temporarily closed.',es:'Cerrado temporalmente.',fr:'Fermé temporairement.',ar:'مغلق مؤقتًا.',ru:'Временно закрыт.',zh:'暂时关闭。',lij:'O l’é temporaneamente serrò.'}
    },
    {
      name: 'Museo Navale di Pegli – Villa Doria Centurione',
      lat: 44.428377,
      lng: 8.815342,
      img: 'musei/museo-navale-pegli.jpg',
      address: 'Piazza Cristoforo Bonavino 7, 16156 Genova Pegli',
      url: 'https://www.museidigenova.it/it/villa-doria-centurione-e-la-torre',
      genovaMappAccess: true,
      desc: {
        it: 'Il Museo Navale di Pegli è ospitato nella cinquecentesca Villa Doria Centurione e raccoglie testimonianze della grande tradizione marinara di Genova e delle Riviere liguri. Le collezioni comprendono materiali databili dal XV al XIX secolo: modelli navali, dipinti, carte, strumenti di navigazione e documenti legati alla vita dei marinai e all’attività dei cantieri liguri. Il museo racconta così diversi secoli di storia marittima, mostrando il profondo rapporto tra il territorio ligure e il mare. La struttura fa parte del sistema Mu.MA – Istituzione Musei del Mare e delle Migrazioni di Genova.',
        en: 'The Pegli Maritime Museum is housed in the 16th-century Villa Doria Centurione and preserves evidence of the great maritime tradition of Genoa and the Ligurian Rivieras. Its collections include objects dating from the 15th to the 19th century, such as ship models, paintings, maps, navigation instruments and documents relating to sailors and Ligurian shipyards. The museum therefore tells the story of several centuries of maritime history and illustrates the deep connection between Liguria and the sea. It is part of Mu.MA, Genoa’s institution dedicated to the Museums of the Sea and Migration.',
        es: 'El Museo Naval de Pegli se encuentra en la Villa Doria Centurione, construida en el siglo XVI, y conserva testimonios de la gran tradición marinera de Génova y de las Rivieras de Liguria. Sus colecciones reúnen materiales comprendidos entre los siglos XV y XIX, entre ellos modelos navales, pinturas, mapas, instrumentos de navegación y documentos relacionados con la vida de los marineros y los astilleros ligures. El museo permite recorrer varios siglos de historia marítima y comprender la profunda relación entre Liguria y el mar. Forma parte del sistema Mu.MA, la institución genovesa dedicada a los Museos del Mar y de las Migraciones.',
        fr: 'Le Musée naval de Pegli est installé dans la Villa Doria Centurione, édifiée au XVIe siècle, et conserve de nombreux témoignages de la grande tradition maritime de Gênes et des Rivieras ligures. Ses collections comprennent des pièces datant du XVe au XIXe siècle : maquettes de navires, peintures, cartes, instruments de navigation et documents liés à la vie des marins et aux chantiers navals ligures. Le musée permet ainsi de parcourir plusieurs siècles d’histoire maritime et de comprendre le lien profond qui unit la Ligurie à la mer. Il fait partie du réseau Mu.MA, l’institution génoise consacrée aux Musées de la Mer et des Migrations.',
        ar: 'يقع متحف بيغلي البحري داخل فيلا دوريا تشينتوريوني التي تعود إلى القرن السادس عشر، ويضم مجموعة من الشهادات والمقتنيات المرتبطة بالتقاليد البحرية العريقة لجنوة وسواحل ليغوريا. تشمل المجموعات مواد تعود إلى الفترة الممتدة من القرن الخامس عشر إلى القرن التاسع عشر، من بينها نماذج للسفن، ولوحات، وخرائط، وأدوات للملاحة، ووثائق تتعلق بحياة البحارة وأحواض بناء السفن في ليغوريا. يروي المتحف بذلك عدة قرون من التاريخ البحري ويبرز العلاقة العميقة بين ليغوريا والبحر. وهو جزء من منظومة Mu.MA لمتاحف البحر والهجرة في جنوة.',
        ru: 'Морской музей Пельи расположен на вилле Дориа Чентурионе XVI века и хранит многочисленные свидетельства богатых морских традиций Генуи и Лигурийской Ривьеры. В коллекции представлены экспонаты XV–XIX веков: модели кораблей, картины, карты, навигационные инструменты и документы, связанные с жизнью моряков и работой лигурийских верфей. Экспозиция охватывает несколько столетий морской истории и показывает, насколько тесно жизнь Лигурии всегда была связана с морем. Музей входит в систему Mu.MA — объединение генуэзских музеев моря и миграции.',
        zh: '佩利海事博物馆位于建于16世纪的多利亚·琴图里奥内别墅内，收藏并展示热那亚及利古里亚海岸悠久航海传统的珍贵资料。馆藏年代从15世纪延续至19世纪，包括船舶模型、绘画、地图、航海仪器，以及与水手生活和利古里亚造船厂有关的历史文件。博物馆通过这些展品讲述数百年的海洋历史，展现利古里亚地区与大海之间深厚而持久的联系。该馆属于热那亚 Mu.MA 海洋与移民博物馆体系。',
        lij: 'O Museo Navâ de Peggi o l’é ospitò inta Villa Doria Centurione, do Çinqueçento, e o conserva testimonianze da grande tradiçion marinara de Zena e de Riviere liguri. E colleçioin comprendan materiali do secolo XV a-o XIX: modelli de navi, quadri, carte, strumenti de navigazion e documenti ligæ a-a vitta di mainæ e a l’attivitæ di cantieri liguri. O museo o racconta coscì ciù secoli de stöia marittima e o mostra o rapporto profondo fra a Liguria e o mâ. O fa parte do sistema Mu.MA, l’istituzion zeneize dedicâ a-i Musei do Mâ e de Migraçioin.'
      },
      access: {it:'Temporaneamente chiuso.',en:'Temporarily closed.',es:'Cerrado temporalmente.',fr:'Fermé temporairement.',ar:'مغلق مؤقتًا.',ru:'Временно закрыт.',zh:'暂时关闭。',lij:'O l’é temporaneamente serrò.'}
    },
    {
      name: 'Genoa Port Center',
      lat: 44.408270,
      lng: 8.921340,
      img: 'musei/museo-genoa-port-center.jpeg',
      address: 'Magazzini del Cotone, Modulo 1 – 2° piano, Area Porto Antico, 16128 Genova',
      url: 'https://www.visitgenoa.it/it/genoa-port-center-centro-educativo-espositivo-del-porto-di-genova',
      genovaMappAccess: true,
      desc: {
        it: 'Il Genoa Port Center è un centro espositivo dedicato al porto di Genova, alle sue attività, alle sue professioni e al suo ruolo economico. Attraverso contenuti didattici e multimediali permette di conoscere dall’interno il funzionamento di uno dei maggiori porti del Mediterraneo, raccontando banchine, navi, cantieri, rimorchiatori, terminal e dogane. Particolare attenzione è dedicata alle numerose professioni che rendono possibile ogni giorno l’attività portuale. Il centro è pensato soprattutto per avvicinare cittadini, studenti e visitatori alla complessa realtà del porto e far comprendere quanto questa infrastruttura sia fondamentale per Genova e per il suo rapporto con il mare.',
        en: 'The Genoa Port Center is an exhibition centre dedicated to the Port of Genoa, its activities, professions and economic role. Through educational and multimedia content, visitors can discover how one of the largest ports in the Mediterranean works from the inside, exploring its docks, ships, shipyards, tugboats, terminals and customs operations. Particular attention is given to the many professions that make the daily operation of the port possible. The centre is designed especially to introduce residents, students and visitors to the complex world of the port and to explain how important this infrastructure is to Genoa and to the city’s historic relationship with the sea.',
        es: 'El Genoa Port Center es un centro expositivo dedicado al puerto de Génova, a sus actividades, profesiones y papel económico. A través de contenidos didácticos y multimedia permite conocer desde dentro el funcionamiento de uno de los mayores puertos del Mediterráneo, descubriendo sus muelles, barcos, astilleros, remolcadores, terminales y aduanas. Se presta especial atención a las numerosas profesiones que hacen posible cada día la actividad portuaria. El centro está pensado especialmente para acercar a ciudadanos, estudiantes y visitantes a la compleja realidad del puerto y explicar la importancia que esta infraestructura tiene para Génova y para su histórica relación con el mar.',
        fr: 'Le Genoa Port Center est un centre d’exposition consacré au port de Gênes, à ses activités, à ses métiers et à son rôle économique. Grâce à des contenus pédagogiques et multimédias, il permet de découvrir de l’intérieur le fonctionnement de l’un des plus grands ports de la Méditerranée, en présentant ses quais, navires, chantiers, remorqueurs, terminaux et services douaniers. Une attention particulière est accordée aux nombreux métiers qui permettent au port de fonctionner chaque jour. Le centre s’adresse notamment aux habitants, aux étudiants et aux visiteurs afin de leur faire découvrir la réalité complexe du port et l’importance de cette infrastructure pour Gênes et son lien historique avec la mer.',
        ar: 'مركز Genoa Port Center هو مركز للمعارض مخصص لميناء جنوة وأنشطته ومهنه ودوره الاقتصادي. من خلال محتويات تعليمية ووسائط متعددة، يتيح للزوار التعرف من الداخل على كيفية عمل أحد أكبر موانئ البحر المتوسط، من الأرصفة والسفن وأحواض بناء السفن إلى القاطرات البحرية والمحطات والجمارك. ويولي المركز اهتماماً خاصاً بالمهن العديدة التي تجعل النشاط اليومي للميناء ممكناً. وقد صُمم بشكل خاص لتعريف السكان والطلاب والزوار بالعالم المعقد للميناء، وإبراز أهمية هذه البنية التحتية لمدينة جنوة ولعلاقتها التاريخية بالبحر.',
        ru: 'Genoa Port Center — выставочный центр, посвящённый Генуэзскому порту, его деятельности, профессиям и экономической роли. С помощью образовательных и мультимедийных материалов посетители могут узнать, как изнутри работает один из крупнейших портов Средиземноморья, познакомиться с его причалами, судами, верфями, буксирами, терминалами и таможенными службами. Особое внимание уделяется многочисленным профессиям, благодаря которым порт функционирует каждый день. Центр создан прежде всего для того, чтобы познакомить жителей города, студентов и туристов со сложным миром порта и показать значение этой инфраструктуры для Генуи и её исторической связи с морем.',
        zh: 'Genoa Port Center 是一座介绍热那亚港及其活动、职业和经济作用的展览中心。通过教育性内容和多媒体展示，参观者可以从内部了解地中海最大港口之一的运作方式，认识码头、船舶、造船厂、拖船、港口终端和海关等不同环节。中心还特别介绍众多与港口日常运行密切相关的职业。这里主要面向市民、学生和游客，希望让公众更深入地认识复杂而庞大的港口体系，并理解这一基础设施对热那亚以及这座城市与海洋之间历史悠久的联系所具有的重要意义。',
        lij: 'O Genoa Port Center o l’é un çentro espositivo dedicò a-o porto de Zena, a-e seu attivitæ, a-e profession e a-o seu ruolo economico. Attraverso contenui didattichi e multimediali o permette de conosce da drento comme o fonçionn-a un di ciù grandi porti do Mediterraneo, raccontando calate, navi, cantieri, rimorchiatoî, terminal e doanne. Un’atençion particolare a l’é dedicâ a-e tante profession che rendan poscibile ogni giorno l’attivitæ portuale. O çentro o l’é pensò sorviatutto pe avvicinâ çitadìn, studenti e visitatoî a-a complessa realtæ do porto e pe fâ capî quanto questa infrastruttua a segge importante pe Zena e pe-o seu rapporto storico co-o mâ.'
      },
      access: {it:'Visitabile su prenotazione.',en:'Visits by reservation only.',es:'Visitable con reserva previa.',fr:'Visite sur réservation.',ar:'يمكن زيارته بالحجز المسبق.',ru:'Посещение по предварительной записи.',zh:'需提前预约参观。',lij:'Se peu visitâ in sciâ prenotazion.'}
    }
  );
})();
